#!/usr/bin/python

import json
import os
import sys

def main():
	args = sys.argv
	if len(args) == 1:
		print("Usage: pyjson JSON_FILENAME")
	else:
		for filename in args[1:]:
			if os.path.isfile(filename):
				try:
					json_object = json.loads(open(filename).read())
					print(json.dumps(json_object, indent=4))
				except Exception as e:
					print(f"  Invalid JSON: '{filename}'")
			else:
				print(f"File not found: '{filename}'")
	pass

if __name__ == '__main__':
	main()

